document.querySelector('#graph').querySelector('table').style= `height:${document.querySelector('#graph').querySelector('table').clientWidth}px`

window.addEventListener('resize',()=>{
    document.querySelector('#graph').querySelector('table').style= `height:${document.querySelector('#graph').querySelector('table').clientWidth}px`
})
document.querySelector('#signOut').addEventListener('click',()=>{
    localStorage.removeItem('DISCData');
    location.replace('./registirationEN.html')
})
/****************************************************/
if(localStorage.getItem('DISCData') == null){
    document.querySelectorAll('section').forEach((e)=>{
        e.classList.add('hidden')
    })
    document.querySelectorAll('h1').forEach((e)=>{
        e.classList.add('hidden')
    })
    document.querySelectorAll('header').forEach((e)=>{
        e.classList.add('hidden')
    })
    document.querySelectorAll('nav').forEach((e)=>{
        e.classList.add('hidden')
    })
}
else{
    document.querySelector('article').classList.add('hidden')
    let data2 = localStorage.getItem('DISCData');
let data = JSON.parse(data2);
let navs = document.querySelector('nav').querySelectorAll('div')
function makeLines(r1,r2,r3,r4){
    let line1 = document.querySelector('#line1');
    let line2 = document.querySelector('#line2');
    let line3 = document.querySelector('#line3');
    //Marking on the rows to be matched
    rows[r1].querySelectorAll('td')[0].innerHTML='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'
    rows[r2].querySelectorAll('td')[1].innerHTML='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'
    rows[r3].querySelectorAll('td')[2].innerHTML='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'
    rows[r4].querySelectorAll('td')[3].innerHTML='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'
    //deleting the other rows
    for(let g=0;g<rows.length;g++){
      if(rows[g].querySelectorAll('td')[0].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'){
        rows[g].querySelectorAll('td')[0].innerHTML='';
      }
      if(rows[g].querySelectorAll('td')[1].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'){
        rows[g].querySelectorAll('td')[1].innerHTML='';
      }
      if(rows[g].querySelectorAll('td')[2].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'){
        rows[g].querySelectorAll('td')[2].innerHTML='';
      }
      if(rows[g].querySelectorAll('td')[3].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'){
        rows[g].querySelectorAll('td')[3].innerHTML='';
      }
      if(rows[g].querySelectorAll('td')[0].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'&&rows[g].querySelectorAll('td')[1].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'&&rows[g].querySelectorAll('td')[2].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>'&&rows[g].querySelectorAll('td')[3].innerHTML!='<span style="display:inline-block;border-radius:50%;border:8px solid #524438;box-shadow:0 0 1px black"></span>')
      rows[g].classList = 'hidden'
    }
    //setting up the coordinates of the lines
    line1.setAttribute('x1',rows[r1].querySelectorAll('td')[0].offsetLeft+0.5*(rows[r1].querySelectorAll('td')[0].clientWidth))
    line1.setAttribute('y1',rows[r1].querySelectorAll('td')[0].offsetTop+0.5*(rows[r1].querySelectorAll('td')[0].clientHeight))
    line1.setAttribute('x2',rows[r2].querySelectorAll('td')[1].offsetLeft+0.5*(rows[r2].querySelectorAll('td')[1].clientWidth))
    line1.setAttribute('y2',rows[r2].querySelectorAll('td')[1].offsetTop+0.5*(rows[r2].querySelectorAll('td')[1].clientHeight))
    line2.setAttribute('x1',rows[r2].querySelectorAll('td')[1].offsetLeft+0.5*(rows[r2].querySelectorAll('td')[1].clientWidth))
    line2.setAttribute('y1',rows[r2].querySelectorAll('td')[1].offsetTop+0.5*(rows[r2].querySelectorAll('td')[1].clientHeight))
    line2.setAttribute('x2',rows[r3].querySelectorAll('td')[2].offsetLeft+0.5*(rows[r3].querySelectorAll('td')[2].clientWidth))
    line2.setAttribute('y2',rows[r3].querySelectorAll('td')[2].offsetTop+0.5*(rows[r3].querySelectorAll('td')[2].clientHeight))
    line3.setAttribute('x1',rows[r3].querySelectorAll('td')[2].offsetLeft+0.5*(rows[r3].querySelectorAll('td')[2].clientWidth))
    line3.setAttribute('y1',rows[r3].querySelectorAll('td')[2].offsetTop+0.5*(rows[r3].querySelectorAll('td')[2].clientHeight))
    line3.setAttribute('x2',rows[r4].querySelectorAll('td')[3].offsetLeft+0.5*(rows[r4].querySelectorAll('td')[3].clientWidth))
    line3.setAttribute('y2',rows[r4].querySelectorAll('td')[3].offsetTop+0.5*(rows[r4].querySelectorAll('td')[3].clientHeight))
  }
  let rows = [];
  let rows1 = document.querySelector('#graph').querySelectorAll('tr');
  for(let l=1;l<rows1.length;l++){
    rows.push(rows1[l])
  }
  console.log(rows1,rows)
  for(let g=0;g<rows.length;g++){
    if((parseInt(rows[g].querySelectorAll('td')[0].innerHTML))==data.D){
      r11=g;
    }
    if((parseInt(rows[g].querySelectorAll('td')[1].innerHTML))==data.I){
      r22=g;
    }
    if((parseInt(rows[g].querySelectorAll('td')[2].innerHTML))==data.S){
      r33=g;
    }
    if((parseInt(rows[g].querySelectorAll('td')[3].innerHTML))==data.C){
      r44=g;
    }
  }
  makeLines(r11,r22,r33,r44)

console.log(data)
document.querySelector('#table').querySelectorAll('tr').forEach((e,i)=>{
    if(i==1){
        e.querySelectorAll('td')[1].innerHTML = data.maxa
        e.querySelectorAll('td')[3].innerHTML = data.mina
        e.querySelectorAll('td')[5].innerHTML = data.D
    }
    if(i==2){
        e.querySelectorAll('td')[1].innerHTML = data.maxb
        e.querySelectorAll('td')[3].innerHTML = data.minb
        e.querySelectorAll('td')[5].innerHTML = data.I
    }
    if(i==3){
        e.querySelectorAll('td')[1].innerHTML = data.maxc
        e.querySelectorAll('td')[3].innerHTML = data.minc
        e.querySelectorAll('td')[5].innerHTML = data.S
    }
    if(i==4){
        e.querySelectorAll('td')[1].innerHTML = data.maxd
        e.querySelectorAll('td')[3].innerHTML = data.mind
        e.querySelectorAll('td')[5].innerHTML = data.C
    }
})

window.addEventListener('resize',()=>{
  makeLines(r11,r22,r33,r44)
  r()
})

/*******************************************************************/
let charactersArr = [],charactersArr2 = [],charactersArr11 = [],charactersArr22 = [],charactersArr33 = []
if(data.mode == 'أ المسيطر'||data.mode == 'D-Dominant'){
    charactersArr.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    if(data.mode2 == 'Dominant'){
        charactersArr2.push('An intense tendency to dominate to the point of dominance, strong, doesn\'t take into account feelings, lack of detail, practices change quickly and radically, practical and highly accomplished, very formal, direct orders, and very firm.','Fit for senior leadership of important short-term projects without taking into account the feeling or entering into details.')
    }
    if(data.mode2 == 'Balanced'){
        charactersArr2.push('One of the best kinds of leaders, controlling with taking into account feelings, leading with some detail, loves to work with senior and middle leaders, practices change quickly and radically, practical and accomplished, loves creativity and theorizing and outstanding leadership.','Fit for senior leadership of important short-term projects, without consideration for feeling with something of feelings and detail.')
    }
    if(data.mode2 == 'Vacillating'){
        charactersArr2.push('Strong tries to balance achievement and relationships, practical, accomplished, take into account feelings, respectful, enters into few important details, has a problem that he is vacillating between fast and gradation, as well as between relationships and work without stability.','Fit for long-term senior leadership, and for important projects, provided that he learns balance.')
    }
    if(data.mode2 == 'Practical'){
        charactersArr2.push('Leading, dominant and very practical. goes into the finest detail, doesn\'t take into account feelings, and prefers achievement over relationships.Fast but less than the rest of the dominant style, centralized, many commands, loves analysis and studies.','Fit for senior leadership in business that has no mistakes, and for short-term projects as well.')
    }
}
if(data.mode == 'ب المؤثر'||data.mode == 'I-Influential'){
    charactersArr.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    if(data.mode2 == 'Catalytic'){
        charactersArr2.push('An intense tendency to encourage and motivate people, eager to love and benefit people, strong, creative, theorist, while not going into detail, practices rapid and radical change, accomplished but less dominant.','Fit for mass or media leadership, as well as theorizing, planning and creativity (without going into details).')
    }
    if(data.mode2 == 'Persuasive'){
        charactersArr2.push('The best kind of leader, he is strong, theorist, creative and lovable, he has a reasonable balance between achievement and relationships with a tendency to take into account emotions, he doesn\'t like details, but he can do so if necessary, he has a very high ability to persuasion.','Fit for long-term senior leadership, as well as media, and loves planning, creativity and persuasion.')
    }
    if(data.mode2 == 'Advisor'){
        charactersArr2.push('An intense tendency for relationships, encouragement and motivation, eager to love, benefit and advise people, but at the expense of achievement and results, goes into details that have to do with people\'s problems and satisfaction and likes theoretical, planning and creativity as well.','Fit for mass leadership (in the social, family and educational fields in particular) and creative in these fields.')
    }
    if(data.mode2 == 'Vacillating '){
        charactersArr2.push('Influential, persuasive, lovable and social, but sometimes excessive at the expense of work and achievement, which makes him stop, enter details, be firm and does not take into account feelings, which makes people annoyed with him, so he returns to try to win their love and satisfaction, thereby the work escapes and thus remains vacillating between the two styles.','Fit for senior leadership in works that does not tolerate errors, as well as for short-term projects provided that he learns balance.')
    }
}
if(data.mode == 'ج المحافظ'||data.mode == 'S-Steady'){
    charactersArr.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
    if(data.mode2 == 'Helpful'){
        charactersArr2.push('An intense tendency for acts in which it comes into contact with people, with few official details, loves to please people and serve them, has something of creativity and willingness to change.','Fit for middle or supervisory leadership, which has contact with people and few official details.')
    }
    if(data.mode2 == 'Sociable'){
        charactersArr2.push('An intense tendency to work in which it comes into contact with people and creativity as well, and is not inclined at all to official works, outgoing, lovable and kind-spoken, successful in public relations and media.','Fit for senior or middle leadership in a few official works with a lot of contact with people.')
    }
    if(data.mode2 == 'Vacillating'){
        charactersArr2.push('He is eager to please people, but at the expense of work, when problems occur, he abandons their satisfaction and becomes official, and when people get upset he gives up work for them, and so without mediation.','Fit for middle or supervisory leadership in which there is considerable contact with people with some detail provided he learn to balance.')
    }
    if(data.mode2 == 'Graded'){
        charactersArr2.push('Balanced between achievement and relationships with a tendency to satisfy people at the expense of work sometimes, he does not like big changes and prefers gradation, stability, regulations, order and work with progression step by step.','Fit for supervisory work in which people are in contact with some details that do not require fast or leaps.')
    }
}
if(data.mode == 'د الواعي'||data.mode == 'C-Conscientious'){
    charactersArr.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
    if(data.mode2 == 'Accurate'){
        charactersArr2.push('An intense tendency to detail and practical aspects, a clear lack of relationships, fun and speech, does not take into account feelings, an intense tendency to order and regulations and a dislike of instability and great change.','Fit for precise detailed official works in which there is less contact with people.')
    }
    if(data.mode2 == 'Graded'){
        charactersArr2.push('Balanced between achievement and relationships with a tendency to formalize and detail, does not like many changes and breaks regulations and order and tends to grade and evolve step by step.','Fit for careful detailed supervisory work in which limited contact with people.')
    }
    if(data.mode2 == 'Vacillating'){
        charactersArr2.push('Professional high attention to detail but at the expense of relationships and when problems occur with people give up his professionalism a little to satisfy them, if the work is disrupted, return to his formality and thus remain vacillating between the two styles without mediation.','Fit for middle or supervisory leadership in which people contact with many operational details provided he learns balance.')
    }
    if(data.mode2 == 'supervisor'){
        charactersArr2.push('clear attention to detail with no regard for people, a strong love for work and a greater tendency for supervisory leadership close to direct practical functions that require accuracy with little leadership, and with distance from contact with people.','Fit for supervisory work that includes details, some leadership work and little contact with people.')
    }
}
if(data.mode == 'ه الموفق'||data.mode == 'N-Facilitator'){
    charactersArr.push('Balanced between relationships and achievement, average in his speed of change, in the middle of almost all traits such as creativity, development, fun, openness, boldness, strength, production, etc.','More creativity, planning, strategy, change, relationship building, recitation, theorizing and creative thinking, and needs to be more in contact with senior leaders and learn from them, especially as he is able to.','Middle leadership where he has the ability to deal with senior leaders as well as supervisory leaders, and is able to go into detail and follow it up while simultaneously building relationships with people.','Because of his moderation and balance, he can deal with all styles.','He can handle all kinds of leaders, although he prefers the influential and then the dominant.','Because of his moderation and balance, the facilitator is easy to deal with and does not need any special abilities or different dealings.','there is no additional traits')
    if(data.mode2 == 'Dominant Facilitator'){
        charactersArr2.push('He has all the traits of a facilitator with a tendency for formality, interest in work and keenness to accomplish with a few details.','Upper middle leadership works that need firmness and formality with few details.')
    }
    if(data.mode2 == 'Influential Facilitator'){
        charactersArr2.push('He has all the traits of a facilitator with some of the traits of an influential, building relationships and the ability to talk and theorize.','Upper middle leadership works which have contact with people or many changes.')
    }
    if(data.mode2 == 'Steady Facilitator'){
        charactersArr2.push('He has all the traits of a facilitator with a keenness to satisfy people, help them and follow their needs.','Sub-intermediate leadership works which have contact with people.')
    }
    if(data.mode2 == 'Conscientious Facilitator'){
        charactersArr2.push('He has all the traits of a facilitator with keenness on details, follow-up, and scrutiny.','Sub-intermediate leadership works that require follow-up details and accuracy.')
    }
}
if(data.mode=='D&I&S'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    charactersArr33.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
}
if(data.mode=='D&I&C'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    charactersArr33.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
if(data.mode=='I&S&C'){
    charactersArr11.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    charactersArr22.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
    charactersArr33.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
if(data.mode=='D&S&C'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
    charactersArr33.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
if(data.mode=='D&I'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
}
if(data.mode=='I&S'){
    charactersArr11.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    charactersArr22.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
}
if(data.mode=='S&C'){
    charactersArr11.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
    charactersArr22.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
if(data.mode=='D&C'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
if(data.mode=='D&S'){
    charactersArr11.push('Bold, fast completion, a few relationships except formal ones, prolific, determined, proud of his opinion, intrepid, ruthless at work, his speech is strong, brave, a guide to others, strong, lover of achievement, strong-willed, ambitious, wins at controversy, adventurous, fast and practical, practical, outspoken, creative, the work first, assertive, worried about work, dominant, strong personality, accepts the challenge, pioneer.','Loosening of control, use nice words and courtesy more, delegate more, not rush in making decisions, don\'t get upset if he is not the first, be patient and not rush the results, consultation more, take into account emotions and feelings, giving a greater part of his time to people, commutation of orders, relaxation and not to constantly stress and worry, easing ideal and accept the "best possible", mitigating self-praise, thank the team he works with and attribute the work to them, reduce criticism of others, review important details.','Leadership work, clear, short-term (projects), which are challenging, require firm decisions, practical creativity, and great achievements. does not like to go into detail, he is bored and likes to change work or position every 3-5 years.','Practical, obedient, high loyalty, few spoken, makes a few mistakes and endures continuous hard work (conscientious and steady style).','The best one to lead him is the "influential" style where it can absorb, observe, and give him a space of freedom for movement and decision, while at the same time it can provide him with creative suggestions and necessary theoretic while taking into account his feelings.','Respect, praise, strong commitment to agreements with him, defer advice and suggestions to a time of calm and leisure (not during work pressure), work hard and accomplish greatly with him, patience with his orders and "cruelty", he means the interest.','He likes to emerge, his orders are direct, he asks a lot to understand, and his decisions are firm and fast<hr>Keen to win, attributes success to himself and talks a lot about the failure of his predecessors<hr>Enjoys taking on new responsibilities, wants to get quick results<hr>Knows what he wants and seeks for it, does consider feelings too much, centralized, gets very upset when he fails<hr>His relationships are not deep (but are often for interests), marginalizing the role of those around him, interrupting the talk<hr>Works on more than one project at the same time, imposes his opinion and does not change it easily<hr>His personality is a tyrant of those around him, (and therefor they fear him more than they love him).')
    charactersArr22.push('Diplomatic, soft, His relationships are extensive, satisfying for those around him, good, his opinions are moderated, generous, courteous, not easily irritated, sociable, cooperating with others, polite, lover of pleasing people, loves to help, outgoing, soft-spoken, moderate, graded, and social, friendly, soothing to others, kind, take into account feelings, sympathetic, very cooperative, interactive, Easy to satisfy, polite, lovable.','Accuracy in work, more discipline, theorizing, creativity, innovative thinking, strategic and operational planning, thinking about major issues and public problems, relieving relationships that waste his time, learning the arts of follow-up and censorship, does not resist change, needing more frankness and clarity and relieves compliments that have a negative impact on work.','Practical matters in which it comes into contact with people, he likes rules and regulations and hates instability, he has no objection to not being responsible, and he has consistency and patience for the same work for a long time.','He can work with all the types and bear them all, whether he is their leader or a subordinate.','The best one to manage him is the influential style, but all styles can lead him.','Clarity, order and regulations with something of freedom when dealing with people to gain their satisfaction. Not to delegate to him in matters that need accuracy, but it is necessary to follow up after him.','Chaotic, especially in his times and papers, he misses details and therefore mistakes are repeated.<hr>Loves movement and not sitting at the desk, loves working with the team.<hr>Has a great role in solving problems and conflicts, flexible and easily changes his attitude to satisfy people.<hr>Good listener, likes to know what others expect of him<hr>Easily deals with different types of people.<hr>Does not like surprises at work, likes praise, is a little firm, and is late in making decisions.')
}
if(data.mode=='I&C'){
    charactersArr11.push('Enthusiastic, much delegated, influential on others, push others to produce, persuasive, thought-provoking, appealing, orally witty, inspirational, encouraging, thinker, lover of theorizing, lovable, high-spirited, carefree, not interested in details, fast and social, outgoing, funny, persuasive, spread pleasure around, confident, delegate, adventurous, capable of shrewdness, Animated, optimistic.','Mitigating theorizing and relationships and focusing more on work and achievement, not exceeding scrutiny of important details, more commitment to business deadlines, more firmness, not content with strategic plans and getting more into operational, mastery of management, organization and censorship, not consulting on everything (decide on urgent or simple matters).','Leadership works that need theorizing and creativity, in which there is a great challenge, or the leadership of large numbers of people, loves to participate in strategic planning and radical change, likes public speaking and media prominence, less interested in detail, prefers collective decision (even he has the ability to be firm), he is bored and likes to change work or position every 3-5 years.','He works easily with all the patterns of people, although he does not tolerate traditionally, he has a special ability to lead the dominant style, as well as leading influencers like him, some team members must be from steady style to cover his urgency less interested in detail.','He endures all kinds of leaders because he takes into account feelings, he does not prefer to be led by the dominant, and he prefers to be led by the influencer because he understands his theorizing, openness and creativity and takes into account his feelings and interests.','Give him a large space of freedom, involve him in planning and change, politely clear and frank, find an appropriate way to cover his urgency and less interested in detail, and because he is quick to trust people there must be someone to warn and alert him constantly.','Makes friends quickly, makes a positive impression (even with strangers) from the first time<hr>Warm and gentle, trusts people too much, likes to impress others<hr>Enjoys praise (and may indeed deserve it), is an accomplished speaker, loves freedom<hr>He does not like formalities, his time and deadlines are relatively flexible<hr>He is often firm but sometimes late in firmness, a good listener<hr>Attributes the work to the team and delegates greatly, working on more than one project at the same time<hr>Likes to consider the origins of things, not their forms.<hr>He misses a lot of details, which causes him problems.')
    charactersArr22.push('Satisfied, strong observant, eager in choosing his relationships, serious in his work, Eager, his opinions are clear, logical, contented, quiet speech, cautious, self-reliant, practical, lover of authenticity, eager to work, accurate, orderly, a few mistakes, gradual and practical, formal, uncurious, humble, prefers privacy, neutral, a few mistakes, conscious, rare mistakes, disciplined, classy.','The art of building and fixing relationships, more fun, creativity, strategic planning, team building, communication, motivation, theorizing and innovative thinking, need to think about general and large issues and problems and relieve the focus on detail, needs to alleviate the ideal, endure people\'s mistakes, be flexible with them, and need not resist change.','Detailed practical matters in which little contact with people, he does not tend to be courtesy, likes frankness, clarity, clear system, detailed precise regulations, has no objection to being irresponsible, has a constant so that he is patient for the same work for long periods.','He likes to lead or work with people of his style only, and he doesn\'t bear the Influential at all where he always disagrees with him, and he\'s hard to lead the dominant, but he can lead the Steady if he needs to.','The best one to lead him is dominant, but all styles can lead him.','Clarity, order, regulations and specific instructions, give him practical detailed work, keep him away from things that need relationships and contact with people, rely on him and trust him in detailed matters.','Exaggerated in order and organization, very upset when wrong.<hr>Loves calm, constantly criticizes the quality of work.<hr>Doesn\'t build new relationships easily.<hr>Doesn\'t like interruptions and tension, he likes norms and standards very much, prefers practical skills and not theory.<hr>He is deeply disturbed and stressed if there is a dispute around him, but he tends to isolate then.')
}
/***************************************/
if(data.mode.includes('&')==false&&data.mode2 != 'There is no detailed style'){
    document.querySelector('aside').querySelector('div').style= 'border:0px;background-color:unset';
    document.querySelector('section').querySelector('section').querySelectorAll('div')[8].innerHTML = charactersArr[0]
    document.querySelector('#res2').classList.remove('hidden')
    document.querySelector('#resBox').querySelectorAll('section')[0].querySelector('h1').innerHTML = `Main Style: ${data.mode}`
    document.querySelector('#resBox').querySelectorAll('section')[1].querySelector('h1').innerHTML = `Detailed Style: ${data.mode2}`
    document.querySelectorAll('.common').forEach((elment)=>{
        elment.querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
            e.addEventListener('click',(evt)=>{
                evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                    elem.style=''
                })
                evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr[i]
                evt.target.style= 'border:0px;background-color:unset';
            })
        })
    })
}
else if(data.mode2 == 'There is no detailed style'){
    document.querySelector('aside').querySelector('div').style= 'border:0px;background-color:unset';
    document.querySelector('section').querySelector('section').querySelectorAll('div')[8].innerHTML = charactersArr[0]
    document.querySelector('#resBox').querySelectorAll('section')[0].querySelector('h1').innerHTML = `Main Style: ${data.mode}`
    document.querySelector('#resBox').querySelectorAll('section')[1].querySelector('h1').innerHTML = `Detailed Style: ${data.mode2}`
    document.querySelectorAll('.common').forEach((elment)=>{
        elment.querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
            e.addEventListener('click',(evt)=>{
                evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                    elem.style=''
                })
                evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr[i]
                evt.target.style= 'border:0px;background-color:unset';
            })
        })
    })
}
else if(data.mode.length==3){
    document.querySelectorAll('.common')[0].querySelectorAll('div')[7].innerHTML = charactersArr11[0]
    document.querySelectorAll('.common')[0].querySelector('h1').innerHTML = `1st Main Style: ${data.mode.slice(0,1)}`
    document.querySelectorAll('.common')[0].querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
        e.addEventListener('click',(evt)=>{
            evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                elem.style=''
            })
            evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr11[i]
            evt.target.style= 'border:0px;background-color:unset';
        })
    })
    let clone = document.querySelector('.common').cloneNode(true)
    document.querySelector('.res').appendChild(clone)
    document.querySelectorAll('.common')[1].querySelectorAll('div')[7].innerHTML = charactersArr22[0]
    document.querySelectorAll('.common')[1].querySelector('h1').innerHTML = `2nd Main Style: ${data.mode.slice(2)}`
    document.querySelectorAll('.common')[1].querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
        e.addEventListener('click',(evt)=>{
            evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                elem.style=''
            })
            evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr22[i]
            evt.target.style= 'border:0px;background-color:unset';
        })
    })
    document.querySelectorAll('aside').forEach((elmnt)=>{
        elmnt.querySelector('div').style= 'border:0px;background-color:unset';
    })
}
else if(data.mode.length==5){
    document.querySelectorAll('.common')[0].querySelectorAll('div')[7].innerHTML = charactersArr11[0]
    document.querySelectorAll('.common')[0].querySelector('h1').innerHTML = `1st Main Style: ${data.mode.slice(0,1)}`
    document.querySelectorAll('.common')[0].querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
        e.addEventListener('click',(evt)=>{
            evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                elem.style=''
            })
            evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr11[i]
            evt.target.style= 'border:0px;background-color:unset';
        })
    })
    let clone = document.querySelector('.common').cloneNode(true)
    document.querySelector('.res').appendChild(clone)
    document.querySelectorAll('.common')[1].querySelectorAll('div')[7].innerHTML = charactersArr22[0]
    document.querySelectorAll('.common')[1].querySelector('h1').innerHTML = `2nd Main Style: ${data.mode.slice(2,3)}`
    document.querySelectorAll('.common')[1].querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
        e.addEventListener('click',(evt)=>{
            evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                elem.style=''
            })
            evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr22[i]
            evt.target.style= 'border:0px;background-color:unset';
        })
    })
    let clone2 = document.querySelector('.common').cloneNode(true)
    document.querySelector('.res').appendChild(clone2)
    document.querySelectorAll('.common')[2].querySelectorAll('div')[7].innerHTML = charactersArr33[0]
    document.querySelectorAll('.common')[2].querySelector('h1').innerHTML = `3rd Main Style: ${data.mode.slice(4)}`
    document.querySelectorAll('.common')[2].querySelector('aside').querySelectorAll('div').forEach((e,i)=>{
        e.addEventListener('click',(evt)=>{
            evt.target.parentElement.querySelectorAll('div').forEach((elem,index) =>{
                elem.style=''
            })
            evt.target.parentElement.parentElement.querySelectorAll('div')[7].innerHTML = charactersArr33[i]
            evt.target.style= 'border:0px;background-color:unset';
        })
    })
    document.querySelectorAll('aside').forEach((elmnt)=>{
        elmnt.querySelector('div').style= 'border:0px;background-color:unset';
    })
}



document.querySelector('header').querySelector('h1').innerHTML+=data.name;
//document.querySelector('aside').querySelectorAll('div')[1].style='border-bottom-left-radius:30px'
/*************************************/

document.querySelector('#res2').querySelector('div').querySelectorAll('div')[0].innerHTML = charactersArr2[0]
document.querySelector('#res2').querySelector('div').querySelectorAll('div')[1].innerHTML = charactersArr2[1]


function r(){
    document.querySelector('#graph').style = `height:${document.querySelector('#table').clientHeight}px`
}

r()
}

